version: 1.0
serverBindAddress: 0.0.0.0:8080
kafka:
  enabled: true
  autocreatetopics: true
  brokers:
    - b-1.dev-kafka.us-west-2.amazonaws.com:9092
    - b-2.dev-kafka.us-west-2.amazonaws.com:9092
    - b-3.dev-kafka.us-west-2.amazonaws.com:9092
  clientID: framework-<yourServiceNameHere>-Dev
monitoring:
  dataDog:
    enabled: true
    namespace: <yourServiceNameHere>
logging:
  format: json
  logLevel: debug
event:
  status:
    topic: event.status

