version: 1.0
serverBindAddress: 0.0.0.0:8080
cron:
  enabled : false
  location : "America_New_York"
pulsar:
  enabled: false
  url: pulsar://localhost:6650
  iothreads: 1
  operationtimeoutseconds: 30
  messagelistenerthreads: 1
  authentication: nil
  numconsumerpertopic: 8
kafka:
  enabled: true
  autocreatetopics: true
  brokers:
    - localhost:9092
  validateTopicExistence: false
  clientID: MyClientIDHere
  maxRetries: 24
  requiredAcks: 1
redis:
  enabled: false
  addr: localhost
  port: 6379
  password:
  db: 0
aerospike:
  enabled: false
  addr: 172.28.128.3
  port: 3000
  writeTimeoutMS: 50
  readTimeoutMS: 50
  validNamespace: test
monitoring:
  dataDog:
    enabled: false
    namespace: SeviceNameHere
    sampleRate: 1.0
logging:
  format: text
  verbose: false
  logLevel: debug
event:
  processor:
    maxRetries: 3
    timeOutSecs: 60
    trackProgressSleep: 1
    bufferSize: 50
    serviceDownHoldSecs: 5000
    runAwayHandlerTimeout: 300000
  status:
    topic: event.status
  dedup:
    duplicationIntervalSecs: 180
    cullPeriod: 60
plan:
  enabled: true
  s3planbucket: plan-task-temp
  localplandir: ../plan/test_json
  allowplanchanges: true
  s3planpollinginterval: 5000
  planapplicationname: PlanName